packages:
  - packages/*

catalog:
  "@types/node": ^24.10.9
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  typescript: ~5.9.3

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - nx
  - vue-demi
