packages:
  - packages/*

catalog:
  '@types/node': ^24.12.2
  es-toolkit: ^1.46.1
  eslint: ^10.2.1
  typescript: ~6.0.3
  zod: "4.3.6"

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - vue-demi
