/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('./app/components/BButton.vue')['default']
    ItemIcon: typeof import('./app/components/ItemIcon.vue')['default']
    ItemNode: typeof import('./app/components/ItemNode.vue')['default']
    RightSidebarCompanion: typeof import('./app/components/RightSidebarCompanion.vue')['default']
    RightSidebarCompanionGrid: typeof import('./app/components/RightSidebarCompanionGrid.vue')['default']
    RightSidebarCompanionItem: typeof import('./app/components/RightSidebarCompanionItem.vue')['default']
    RightSidebarEntityGrid: typeof import('./app/components/RightSidebarEntityGrid.vue')['default']
    RightSidebarItem: typeof import('./app/components/RightSidebarItem.vue')['default']
    RightSidebarItemGrid: typeof import('./app/components/RightSidebarItemGrid.vue')['default']
    RightSidebarLocation: typeof import('./app/components/RightSidebarLocation.vue')['default']
    RightSidebarLocationGrid: typeof import('./app/components/RightSidebarLocationGrid.vue')['default']
    RightSidebarLocationItem: typeof import('./app/components/RightSidebarLocationItem.vue')['default']
    ThePlanningCanvas: typeof import('./app/components/ThePlanningCanvas.vue')['default']
    TheRightSidebar: typeof import('./app/components/TheRightSidebar.vue')['default']
  }
}
