/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('./app/components/BButton.vue')['default']
    ItemIcon: typeof import('./app/components/ItemIcon.vue')['default']
    ItemNode: typeof import('./app/components/ItemNode.vue')['default']
    RightSidebarItem: typeof import('./app/components/RightSidebarItem.vue')['default']
    RightSidebarItemGrid: typeof import('./app/components/RightSidebarItemGrid.vue')['default']
    ThePlanningCanvas: typeof import('./app/components/ThePlanningCanvas.vue')['default']
    TheRightSidebar: typeof import('./app/components/TheRightSidebar.vue')['default']
  }
}
