/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategorySelect: typeof import('./app/components/CategorySelect.vue')['default']
    EndNode: typeof import('./app/components/Flow/EndNode.vue')['default']
    FlowNodeControlElement: typeof import('./app/components/Flow/FlowNodeControlElement.vue')['default']
    FlowNodeControls: typeof import('./app/components/Flow/FlowNodeControls.vue')['default']
    ItemIcon: typeof import('./app/components/Item/ItemIcon.vue')['default']
    ItemNode: typeof import('./app/components/Item/ItemNode.vue')['default']
    NoteNode: typeof import('./app/components/Flow/NoteNode.vue')['default']
    RightSidebarCompanion: typeof import('./app/components/Companion/RightSidebarCompanion.vue')['default']
    RightSidebarCompanionGrid: typeof import('./app/components/Companion/RightSidebarCompanionGrid.vue')['default']
    RightSidebarEntityGrid: typeof import('./app/components/RightSidebarEntityGrid.vue')['default']
    RightSidebarItem: typeof import('./app/components/Item/RightSidebarItem.vue')['default']
    RightSidebarItemGrid: typeof import('./app/components/Item/RightSidebarItemGrid.vue')['default']
    RightSidebarLocation: typeof import('./app/components/Location/RightSidebarLocation.vue')['default']
    RightSidebarLocationGrid: typeof import('./app/components/Location/RightSidebarLocationGrid.vue')['default']
    StartNode: typeof import('./app/components/Flow/StartNode.vue')['default']
    TheFlow: typeof import('./app/components/TheFlow.vue')['default']
    TheRightSidebar: typeof import('./app/components/TheRightSidebar.vue')['default']
  }
}
